name: Build lara IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Archive
        run: |
          cd lara-0.2
          xcodebuild -project lara.xcodeproj \
  -scheme lara \
  -configuration Release \
  -archivePath ../build/lara.xcarchive \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  archive

      
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: lara-ipa
          path: build/lara.xcarchive
